# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tercer parcial de Machine Learning
author: Valentina Cabrera, Valentina Bustamante
logo: logo.png

execute:
  execute_notebooks: 'off'


latex:
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
